apiVersion: apps/v1
kind: Deployment
metadata:
  name: labelapp-deployment
  labels:
    app: weather-exporter
  namespace: weather-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
     app: weather-exporter
  template:
    metadata:
      labels:
        app: weather-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9265"
        prometheus.io/path: "/"
    spec:
      containers:
        - name: weather-exporter
          image: stephw/weather-exporter:latest
          ports:
            - containerPort: 9265
          env:
            - name: DARK_SKY_API_KEY
              value: "b85a4c9fce9d5c1a6ea49e69886332ac"
            - name: ENDPOINT_PORT
              value: "9265"
            - name: CITIES
              value: "paris"
            - name: SCRAPE_INTERVAL
              value: "10000"